name: Motivational Quotes
on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Fetch motivational quote
      run: |
        # Fetch a motivational quote from the API
        quote=$(curl -s https://api.api-ninjas.com/v1/quotes?category=attitude)
        
        # Extract the quote text from the JSON response
        quote_text=$(echo "$quote" | jq -r '.[0].quote')
        
        # Get the current timestamp
        timestamp=$(date +"%Y-%m-%d %T")
        
        # Check if the quote already exists in quotes.txt
        if ! grep -qF "$quote_text" quotes.txt; then
          # Append the quote along with additional details to the quotes.txt file
          echo "Timestamp: $timestamp" >> quotes.txt
          echo "Quote: $quote_text" >> quotes.txt
          echo "" >> quotes.txt
          
          # Configure Git user for the commit
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Stage the changes (add quotes.txt)
          git add quotes.txt
          
          # Commit the changes with a descriptive message
          git commit -m "Add new motivational quote: $timestamp"
          
          # Push the changes to the repository
          git push
        fi
