name: Daily Commit with Inspirational Quote

on:
  schedule:
    - cron: '* * * * *' # Runs every minute for testing

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: 'main' # Specify the branch here

    - name: Set up Git
      run: |
        echo "Setting up Git"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Fetch Inspirational Quote
      run: |
        echo "Fetching Inspirational Quote"
        QUOTE=$(curl -s 'https://zenquotes.io/api/random' | jq -r '.[0].q')
        COMMIT_TIME=$(date '+%d %B of %Y in %H hours %M minutes')
        echo "Fetched Inspirational Quote at $COMMIT_TIME - \"$QUOTE\"" >> example.txt

    - name: Commit Changes
      run: |
        echo "Committing Changes"
        git add example.txt
        git status  # Add this for debugging purposes
        git commit -m "Auto commit with inspirational quote $(date +%F)"
        git push origin main # Assuming the branch name is main, change if needed
