name: Motivational Push (Every Hour)

on:
  schedule:
    - cron: '*/5 * * * *'  # Every hour (change cron for different intervals)

jobs:
  quote-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checkout repository code

      - name: Fetch Inspirational Quote (with error handling)
        run: |
          QUOTE=$(curl -sSL 'https://zenquotes.io/api/random?category=programming' | jq -r '.[0].q' || echo "Failed to fetch quote")
          COMMIT_TIME=$(date '+%d %B %Y, %H:%M:%S %Z')  # Include time zone
          COMMIT_MESSAGE="**Motivation Alert!** Quote: \"$QUOTE\" - $COMMIT_TIME"

      - name: Add a Cool ASCII Art Banner  # Optional
        run: |
          echo "
           _   _ _   _ _   _   _ 
          | | | | | | | | | | | |
          | |_| | | | | | | | | |
          |  _  | | | | | | | | |
          | | | | |_| |_| |_| |_|
          |_|_|_|_  _|_|_|   _| |
                | |     (_|  | |
                |_|          |_|
          " >> example.txt

      - name: Append Motivational Quote
        run: |
          echo "$COMMIT_MESSAGE" >> example.txt

      - name: Add and Commit Changes
        run: |
          git add example.txt
          git commit -m "$COMMIT_MESSAGE"

      - name: Push Changes (check permissions)  # Optional
        run: git push origin main
