name: Daily Commit with Inspirational Quote

on:
  workflow_run:
    workflows: ["Daily Trigger"]
    types:
      - completed

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: 'main' # Specify the branch here

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Fetch Inspirational Quote
      run: |
        QUOTE=$(curl -s 'https://zenquotes.io/api/random' | jq -r '.[0].q')
        COMMIT_TIME=$(date '+%d %B of %Y in %H hours %M minutes')
        echo "Fetched Inspirational Quote at $COMMIT_TIME - \"$QUOTE\"" >> example.txt

    - name: Commit Changes
      run: |
        git add example.txt
        git status  # Add this for debugging purposes
        git commit -m "Auto commit with inspirational quote $(date +%F)"

    - name: Pull changes from remote
      run: git pull origin main

    - name: Push changes to remote
      run: git push origin main
