name: Motivational Quotes
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch motivational quote
      run: |
        quote=$(curl -s https://programming-quotes-api.herokuapp.com/quotes/random)
        echo "$quote" | jq -r '.en' >> quotes.txt
        echo "Commit details:" >> quotes.txt
        echo "----------------------------------------" >> quotes.txt
        echo "$(git log -1 --pretty=format:'Commit: %h%nAuthor: %an%nDate: %ar%nMessage: %s')" >> quotes.txt
        echo "" >> quotes.txt
    - name: Check if file has changed
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "No changes detected."
          exit 0
        else
          echo "Changes detected."
          exit 1
        fi
    - name: Commit changes
      if: steps.check_changes.outcome == 'failure'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add quotes.txt
        git commit -m "Add motivational quote and commit details"
        git pull origin main --no-edit
        git push
      continue-on-error: true
